import os, glob

# The following 8 arrays contain the extracted compile-time 
# configuration options from the sqlite using the "./configure --help"
optional_features = ["--disable%s" % p for p in ("-option-checking",
                                                    "-libtool-lock",
                                                    "-largefile",
                                                    "-threadsafe",
                                                    "-tcl",
                                                    "-readline",
                                                    "-amalgamation",
                                                    "-load-extension",
                                                    "-math"
                                                )]              

optional_features_02 = ["--enable%s" % p for p in ("-shared=no",
                                                    "-static",
                                                    "-fast-install",
                                                    "-releasemode",
                                                    "-tempstore",
                                                    "-editline",
                                                    "-debug",
                                                    "-all",
                                                    "-memsys5",
                                                    "-memsys3",
                                                    "-fts3",
                                                    "-fts4",
                                                    "-fts5",
                                                    "-json1",
                                                    "-update-limit",
                                                    "-geopoly",
                                                    "-rtree",
                                                    "-session",
                                                    "-gcov")]

optional_packages = ["--with%s" % p for p in ("-pic",
                                                "-gnu-ld",
                                                "-tcl=/usr/lib64"
                                                #"-readline-lib",
                                                #"-readline-inc"
                                                )] # 33 - 2 = 31 

# Adding the single configurations to an array 
def extractDigits(lst):
    res = []
    for el in lst:
        sub = el.split(', ')
        res.append(sub)
    #print(res)
    return(res)
   

# All single configurations                   
single_configurations_01 = extractDigits(optional_features)
single_configurations_02 = extractDigits(optional_features_02)
single_configurations_03 = extractDigits(optional_packages)

# Adding the sample configuration sets (generated by FeatureIDE) to an array
sample_configurations = []

# for variant in glob.glob("measures/products/*.config"):
for variant in glob.glob("measures/products_2-200/*.config"):
    lineList = list()
    with open(variant) as f:
        for line in f:
            lineList = [line.rstrip('\n') for line in open(variant)]
        sample_configurations.append(lineList)

#print(sample_configurations)
print(*single_configurations_01,*single_configurations_02,*single_configurations_03)


# All single and sample configurations, 
# which will be used to measure the changes on
# the binary size and number of gadgets in x264
all_options =  [*sample_configurations]